### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by devskar** [layla-oskar-schule/VinopinionsApi#39]
username should only consist of numbers and letters (has to be url conform)

**Comment by devskar** [comment]
Currently there is very little validation of anything

**Comment by tschokri** [comment]
Use @IsUUID() for uuids

**Comment by devskar** [comment]
I feel like many issues with this are already fixed by the implementation of 
https://github.com/layla-oskar-schule/VinopinionsApi/blob/4112af76fef5b81e012aa3cd93161ee064bbabf2/src/main.ts#L28

Now it is all about adding decorators to our entities and dto's that will be validated by the pipe

**Comment by devskar** [comment]
> username should only consist of numbers and letters (has to be url conform)

I believe that our current setup: a-z A-Z 0-9 _ .  is also url conform and should be fine

**Comment by devskar** [comment]
Validation has been added in #68
